server:
  port: 8083

eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
    
spring:
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
    datasource:
        url=jdbc: h2:mem:db
    jpa:
        show-sql: true