server:
  port: 8081

spring:
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
    datasource:
        url=jdbc: h2:mem:db
    jpa:
        show-sql: true
